### ISSUE TITLE
[SIGN-IN / SIGN-UP] - Design mock up regarding navigation bar

### ISSUE THREAD

**Issue by bunsalcoder** [pnc-virtual-company/2021-G4-VC2-PART2#6]
You are responsible for designing mock up on navigation bar including the visibility or invisibility of the user's role.

**Comment by sotheanchoun** [comment]
Dear Project Manager @Sovanda-chib,

This is my navigation mock-up, I have done it many days but I forgot to push it.

![image](https://user-images.githubusercontent.com/77543006/146940439-bfa86fbc-6000-4d30-a2b3-78313f282c54.png)
