### ISSUE TITLE
[SIGN-IN / SIGN-UP] - Design mock up regarding sign-in / sign-up

### ISSUE THREAD

**Issue by bunsalcoder** [pnc-virtual-company/2021-G4-VC2-PART2#7]
You have to design a mock up regarding sign-in and sign-up form.

**Comment by bunsalcoder** [comment]
Dear Project Manager @Sovanda-chib,

Here is the mock up of my sign in form, could you please check it? 

![image](https://user-images.githubusercontent.com/77948541/146513369-ea6b9d56-08e9-4c70-9176-d47926e3c0df.png)

**Comment by mengheangpho** [comment]
Dear Project Manager @Sovanda-chib,

Here is the mock up of my sign up form, could you please check it?
![image](https://user-images.githubusercontent.com/77542463/146513630-b6d1ecb7-0f42-4256-928b-667f735306cd.png)

**Comment by Sovanda-chib** [comment]
Very good!
