### ISSUE TITLE
[SIGN-IN / SIGN-UP] - Design mock up regarding alumni profile view

### ISSUE THREAD

**Issue by bunsalcoder** [pnc-virtual-company/2021-G4-VC2-PART2#8]
You have to design a mock up about alumni profile view, how we see detail on the profile of each alumni.

**Comment by MengHour4-4** [comment]
Dear Project Manager @Sovanda-chib,

This is my alumni mock-up, could you please check it?

![image](https://user-images.githubusercontent.com/92873558/146939936-a83f617b-39c6-42cc-8027-4ef4279162b7.png)
![image](https://user-images.githubusercontent.com/92873558/146939953-4affa88e-163c-4042-a8e3-7b3defc025fe.png)
